SKINS = {
    "Desert Eagle | Синяя фанера": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/deagle_blue_plywood.png", "price": 22, "type": "weapon"},
    "MAC-10 | Лазурный хищник": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/mac10_azure.png", "price": 71, "type": "weapon"},
    "Сувенирный Desert Eagle | Недовольство": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/deagle_discontent.png", "price": 76, "type": "weapon"},
    "M4A1-S | Северный лес": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/m4a1s_northern_forest.png", "price": 11, "type": "weapon"},
    "Револьвер R8 | Пламя": {"rarity": "red", "color": "#ff3b5c", "image": "/static/skins/r8_flame.png", "price": 471, "type": "weapon"},
    "UMP-45 | Каркас": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/ump45_carcass.png", "price": 114, "type": "weapon"},
    "Glock-18 | Ласка": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/glock_weasel.png", "price": 96, "type": "weapon"},
    "G3SG1 | Чёрный песок": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/g3sg1_black_sand.png", "price": 78, "type": "weapon"},
    "Negev | Погрузчик": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/negev_loader.png", "price": 102, "type": "weapon"},
    "Dual Berettas | Пантера": {"rarity": "red", "color": "#ff3b5c", "image": "/static/skins/dual_panther.png", "price": 302, "type": "weapon"},
    "M4A4 | Пиксельный камуфляж «Город»": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/m4a4_pixel.png", "price": 11, "type": "weapon"},
    "SSG 08 | Ручной тормоз": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/ssg08_handbrake.png", "price": 81, "type": "weapon"},
    "Desert Eagle | Стрелковая дисциплина": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/deagle_marksman.png", "price": 55, "type": "weapon"},
    "P90 | Элитное снаряжение": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/p90_elite.png", "price": 34, "type": "weapon"},
    "Tec-9 | Треснувший опал": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/tec9_opal.png", "price": 21, "type": "weapon"},
    "P90 | Воин дорог": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/p90_roadwarrior.png", "price": 110, "type": "weapon"},
    "Glock-18 | Призраки": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/glock_ghosts.png", "price": 42, "type": "weapon"},
    "MP5-SD | Гаусс": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/mp5_gauss.png", "price": 68, "type": "weapon"},
    "AWP | Разлив мышьяка": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/awp_arsenic.png", "price": 25, "type": "weapon"},
    "M4A1-S | Смешанный камуфляж": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/m4a1s_mixed.png", "price": 18, "type": "weapon"},
    "P2000 | Янтарный градиент": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/p2000_amber.png", "price": 51, "type": "weapon"},
    "StatTrak™ M4A1-S | Ночной ужас": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/m4a1s_night_terror.png", "price": 91, "type": "weapon"},
    "SG 553 | Колония IV": {"rarity": "red", "color": "#ff3b5c", "image": "/static/skins/sg553_colony.png", "price": 650, "type": "weapon"},
    "CZ75-Auto | Желтый жакет": {"rarity": "red", "color": "#ff3b5c", "image": "/static/skins/cz75_yellow_jacket.png", "price": 312, "type": "weapon"},
    "StatTrak™ Desert Eagle | Оксидное пламя": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/deagle_oxide.png", "price": 70, "type": "weapon"},
    "USP-S | Ночные операции": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/usps_night_ops.png", "price": 17, "type": "weapon"},
    "USP-S | Тропический бриз": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/usps_tropical.png", "price": 25, "type": "weapon"},
    "USP-S | Проводник": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/usps_conductor.png", "price": 57, "type": "weapon"},
    "StatTrak™ MAG-7 | Ядро кобальта": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/mag7_cobalt.png", "price": 94, "type": "weapon"},
    "Dual Berettas | Протектор": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/dual_protector.png", "price": 73, "type": "weapon"},
    "Five-SeveN | Испытание огнём": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/fiveseven_fire_test.png", "price": 14, "type": "weapon"},
    "Desert Eagle | «Дейли Дигл»": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/deagle_daily.png", "price": 16, "type": "weapon"},
    "M4A1-S | Электрум": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/m4a1s_electrum.png", "price": 69, "type": "weapon"},
    "SCAR-20 | Генератор": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/scar20_generator.png", "price": 105, "type": "weapon"},
    "USP-S | Пустынная тактика": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/usps_desert.png", "price": 17, "type": "weapon"},
    "StatTrak™ SG 553 | Дикая моль": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/sg553_moth.png", "price": 146, "type": "weapon"},
    "AK-47 | Афродита": {"rarity": "red", "color": "#ff3b5c", "image": "/static/skins/ak47_aphrodite.png", "price": 1105, "type": "weapon"},
    "P250 | Киберпанцирь": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/p250_cyber.png", "price": 41, "type": "weapon"},
    "P90 | Ностальгия": {"rarity": "red", "color": "#ff3b5c", "image": "/static/skins/p90_nostalgia.png", "price": 323, "type": "weapon"},
    "SSG 08 | Некромант": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/ssg08_necromancer.png", "price": 64, "type": "weapon"},
    "Negev | Крикун": {"rarity": "pink", "color": "#e040fb", "image": "/static/skins/negev_screamer.png", "price": 71, "type": "weapon"},
    "P90 | Чертёж-негатив": {"rarity": "blue", "color": "#5b8def", "image": "/static/skins/p90_blueprint.png", "price": 15, "type": "weapon"},
}

UPGRADE_COST = 500
UPGRADE_REQUIRED = 10
RARITY_ORDER = {"blue": 1, "pink": 2, "red": 3, "gold": 4}

CASES = {
    "luka": {
        "name": "Luka",
        "image": "/static/cases/luka.png",
        "price": 29,
        "type": "weapon",
        "items": [
            {"skin": "Desert Eagle | Синяя фанера", "chance": 10},
            {"skin": "MAC-10 | Лазурный хищник", "chance": 6},
            {"skin": "Сувенирный Desert Eagle | Недовольство", "chance": 5},
            {"skin": "M4A1-S | Северный лес", "chance": 12},
            {"skin": "Револьвер R8 | Пламя", "chance": 0.5},
            {"skin": "UMP-45 | Каркас", "chance": 4},
            {"skin": "Glock-18 | Ласка", "chance": 5},
            {"skin": "G3SG1 | Чёрный песок", "chance": 6},
            {"skin": "Negev | Погрузчик", "chance": 4},
            {"skin": "Dual Berettas | Пантера", "chance": 1},
            {"skin": "M4A4 | Пиксельный камуфляж «Город»", "chance": 12},
            {"skin": "SSG 08 | Ручной тормоз", "chance": 6},
            {"skin": "Desert Eagle | Стрелковая дисциплина", "chance": 7},
            {"skin": "P90 | Элитное снаряжение", "chance": 8},
            {"skin": "Tec-9 | Треснувший опал", "chance": 10},
            {"skin": "P90 | Воин дорог", "chance": 4},
            {"skin": "Glock-18 | Призраки", "chance": 8},
            {"skin": "MP5-SD | Гаусс", "chance": 6},
            {"skin": "AWP | Разлив мышьяка", "chance": 10},
            {"skin": "M4A1-S | Смешанный камуфляж", "chance": 11},
            {"skin": "P2000 | Янтарный градиент", "chance": 7},
            {"skin": "StatTrak™ M4A1-S | Ночной ужас", "chance": 5},
            {"skin": "SG 553 | Колония IV", "chance": 0.3},
            {"skin": "CZ75-Auto | Желтый жакет", "chance": 1},
            {"skin": "StatTrak™ Desert Eagle | Оксидное пламя", "chance": 6},
            {"skin": "USP-S | Ночные операции", "chance": 11},
            {"skin": "USP-S | Тропический бриз", "chance": 10},
            {"skin": "USP-S | Проводник", "chance": 7},
            {"skin": "StatTrak™ MAG-7 | Ядро кобальта", "chance": 5},
            {"skin": "Dual Berettas | Протектор", "chance": 6},
            {"skin": "Five-SeveN | Испытание огнём", "chance": 12},
            {"skin": "Desert Eagle | «Дейли Дигл»", "chance": 11},
            {"skin": "M4A1-S | Электрум", "chance": 6},
            {"skin": "SCAR-20 | Генератор", "chance": 4},
            {"skin": "USP-S | Пустынная тактика", "chance": 11},
            {"skin": "StatTrak™ SG 553 | Дикая моль", "chance": 3},
            {"skin": "AK-47 | Афродита", "chance": 0.2},
            {"skin": "P250 | Киберпанцирь", "chance": 8},
            {"skin": "P90 | Ностальгия", "chance": 1},
            {"skin": "SSG 08 | Некромант", "chance": 6},
            {"skin": "Negev | Крикун", "chance": 6},
            {"skin": "P90 | Чертёж-негатив", "chance": 12},
        ]
    }
}
